#
#	{SCRIPT NAME} 1.0.0
#	
#	Created for as a commission. You do not have the rights to resell/redistribute.
#	Copyright © 2021 Baylor Henshaw <baylor@henshaw.me>
#
#	Written by Baylor Henshaw (https://baezor.com/)
#

#
#	Configuration
#

# Options
options:
	
	# Style Options
	prefix: &3*REPLACE_WITH_PREFIX* &8»
	color.1: &7
	color.2: &b
	color.3: &3

	# Other Options
	debug: true
	version: 1.0.0
	storage: *REPLACE_WITH_STORAGE*